server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

    
spring:
    application:
        name: voucherict
    profiles:
        active: dev
    jackson:
        serialization.indent_output: true 
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: test
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9300
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard            
        
        
logging:
  level:
    ROOT: INFO
    com.stasbranger.voucherict: INFO        